### ISSUE TITLE
Real "max_detect_distance" is no way greater than 5 meters

### ISSUE THREAD

**Issue by ItsJas** [angusleigh/leg_tracker#3]
Hi!
_First of all , thanks for your great work!_

I was testing the code in order to do a demo [like this one](https://www.youtube.com/watch?v=F2Qx3O5AyBs) And I'm getting some where but I do need the robot to track or at least detect me even when we are 7 or 10 meters apart.
For instance even though I increase the `max_detect_distance` the 'real' maximum detection distance is around 4 or 5 meters.
Does this have something to do with a training parameter I'm missing or with the `local_occupancy_grid_map` node. I'm actually taking this [demo launch file](https://github.com/angusleigh/leg_tracker/blob/indigo/launch/demos/demo_moving_super_crowded.launch) as  starting point.

Your help would be appreciated,
Regards,
ItsJas.

**Comment by ItsJas** [comment]
> Does this have something to do with a training parameter I'm missing ?

Yes !? 
It is set in the training launch file: [extract_positive_training_clusters_res=0.33.launch](https://github.com/angusleigh/leg_tracker/blob/indigo/launch/training/extract_positive_training_clusters_res%3D0.33.launch)
`<param name="max_dist" value="5"/> `
But were this launch file and [bag files](https://github.com/angusleigh/leg_tracker/tree/indigo/rosbags/training_scans_res%3D0.33) used for the training to produce the [trained_leg_detector_res=0.33.yaml ](https://github.com/angusleigh/leg_tracker/blob/indigo/config/trained_leg_detector_res=0.33.yaml) file
So in this case do I have to redo the hole training process with a bigger `max_dist` ?
Can I use the provided training bag files or do I have to create new ones?
How far can the `max_dist` get?

_Sorry for all these questions_.

**Comment by angusleigh** [comment]
Max detection distance could also be limited by the laser scan point clustering, since fewer points will land on the person and they'll be further apart from each other. Trying increasing cluster_dist_euclid and setting min_points_per_cluster to 1. 

You could also try checking the output of detect_leg_clusters in rviz to make sure the laser points are being successfully clustered. If so, you should see the spheres appearing in the centre of clusters, as in here: https://youtu.be/F2Qx3O5AyBs?t=27s.
