### ISSUE TITLE
Issue of using pykalman

### ISSUE THREAD

**Issue by samjang9509** [angusleigh/leg_tracker#31]
Dear angusleigh
First of all thank you for allowing your work in the open for us, I have personally been learning a lot.
I just had one question though, I was wondering if you knew of any kind of other kalman filters that we can use other than the give pykalman.

**Comment by angusleigh** [comment]
Hi samjang9505! Thanks for you interest. I have not tried anything else myself, but I imagine it to be quite interchangeable, since Kalman filters are quite popular and we are only using very basic Kalman filter functionality in this repo. You could maybe give [FilterPy](https://filterpy.readthedocs.io/en/latest/index.html) a shot, or perhaps consider using the [provided docker](https://github.com/angusleigh/leg_tracker?tab=readme-ov-file#docker) instead?

**Comment by samjang9509** [comment]
Thank you so much for the reply.
As recommended I am trying to use the provided docker but it seems like make docker_build command is not working.
I have downloaded docker system in itself, I believe, is there something that I must do before I continue with using docker?

**Comment by angusleigh** [comment]
If you share the docker error message, I could take a look. In general, if would help to make sure your docker installation is working by testing it with other repos on github too.
