### ISSUE TITLE
Publish Occluded Issue - person track drift off

### ISSUE THREAD

**Issue by candersen10** [angusleigh/leg_tracker#4]
Hello,

We have been running the Leg Tracker, and when we set Publish Occluded to true, the leg tracker tries to give a continuous output, but if it loses the person being tracked, it continues to publish a person track that drifts off to a random place and then disappears rather than disappearing quickly.

If we set publish occluded to false, we get jitters in the person tracked output (i.e. person tracked, then a split second loss of the person, then reacquiring them).

Has anyone seen or solved this issue?  It seems to be a glitch because the tracked person, once lost, will drift off randomly with published occluded set to true for nearly a second or two.

**Comment by candersen10** [comment]
Here is a video that shows the issue: https://youtu.be/iZc0pkGgpME

Drifts happen at 11 seconds and 20 seconds.  What we would like to see is for the drifts to stop almost immediately, and for the direction to be consistent (i.e. not shown in the video, but at times the drifts will seem to be very opposite whatever direction the person being tracked is traveling).

**Comment by angusleigh** [comment]
Thanks for the detailed report!

The drift your describing is actually by design. We use a constant-velocity motion model for predicting future location, so when there's no new localization information (i.e., the person is occluded), their estimated position will continue with the velocity they had just before they disappeared. 

If you want to use a constant-position motion model, then you can try changing the transition matrix in joint_leg_tracker.py to: 

\# Constant position motion model
transition_matrix = np.array([[1, 0, 0, 0],
                                                 [0, 1, 0, 0],
                                                 [0, 0, 0, 0],
                                                 [0, 0, 0, 0]])  

but I'm not sure that would improve things overall. 

You might also want to try only updating the Kalman after an observation (and skip updating otherwise). To do this, move the line "track.update(observations)" up to be within the scope of "if matched_detection:".

The cases you describe where the drift goes in the opposite direction sound like they might be caused my measurement errors but I'm not sure. If you can post a video of this happening, it might help.

**Comment by nemo113** [comment]
> Here is a video that shows the issue: https://youtu.be/iZc0pkGgpME
> 
> Drifts happen at 11 seconds and 20 seconds. What we would like to see is for the drifts to stop almost immediately, and for the direction to be consistent (i.e. not shown in the video, but at times the drifts will seem to be very opposite whatever direction the person being tracked is traveling).
Hello,  I have the same problem.I try to solve by using  Constant position motion model ,but it doesn't work. Did you solved this issue?
Thanks!
